- name: copy etcd binarys
  synchronize:
    src: "{{ item }}"
    dest: /usr/bin/
  with_items:
    - "/home/nick/Downloads/etcd"
    - "/home/nick/Downloads/etcdctl"

- name: create etcd data dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ etcd_confdir }}"
    - "{{ etcd_datadir }}"

- name: create etcd service
  template:
    src: etcd_service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
  notify:
    - systemd reload
