# - name: set datasource connection-url
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">'
#     regexp: '<connection-url>.*</connection-url>'
#     line: <connection-url>jdbc:mariadb://{{ db_host }}/{{ role_name }}</connection-url>
#     firstmatch: true

# - name: set datasource driver
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">'
#     regexp: '<driver>.*</driver>'
#     line: <driver>mariadb</driver>
#     firstmatch: true

# - name: set db user
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">'
#     regexp: '<user-name>.*</user-name>'
#     line: <user-name>{{ app_user }}</user-name>
#     firstmatch: true

# - name: set db password
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">'
#     regexp: '<password>.*</password>'
#     line: <password>{{ app_password }}</password>
#     firstmatch: true

# - name: set db driver
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<drivers>'
#     regexp: '<driver .*>'
#     line: |
#         <driver name="mariadb" module="org.mariadb.jdbc">
#             <xa-datasource-class>org.mariadb.jdbc.MySQLDataSource</xa-datasource-class>
#         </driver>
#     firstmatch: true

# - name: set db password
#   lineinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     insertafter: '<drivers>'
#     regexp: '<xa-datasource-class>.*</xa-datasource-class>'
#     line: <xa-datasource-class>org.mariadb.jdbc.MySQLDataSource</xa-datasource-class>
#     firstmatch: true

# - name: add datasource configuration
#   blockinfile:
#     path: "{{ app_path }}/standalone/configuration/standalone.xml"
#     backup: true
#     marker: ""
#     insertafter: '.*<subsystem xmlns="urn:jboss:domain:datasources:5.0">$'
#     block: >+
#         <datasources>
#             <datasource jndi-name="java:jboss/datasources/KeycloakDS" pool-name="KeycloakDS" enabled="true" use-java-context="true">
#                 <connection-url>jdbc:mariadb://{{ db_host }}/{{ role_name }}</connection-url>
#                 <driver>mariadb</driver>
#                 <pool>
#                     <flush-strategy>IdleConnections</flush-strategy>
#                 </pool>
#                 <security>
#                     <user-name>{{ app_user }}</user-name>
#                     <password>{{ app_password }}</password>
#                 </security>
#                 <validation>
#                     <check-valid-connection-sql>SELECT 1</check-valid-connection-sql>
#                     <background-validation>true</background-validation>
#                     <background-validation-millis>60000</background-validation-millis>
#                 </validation>
#             </datasource>
#             <drivers>
#                 <driver name="mariadb" module="org.mariadb.jdbc">
#                     <xa-datasource-class>org.mariadb.jdbc.MySQLDataSource</xa-datasource-class>
#                 </driver>
#             </drivers>
#         </datasources>

- name: create module path
  file:
    path: "{{ app_path }}/modules/system/layers/base/org/mariadb/jdbc/main/"
    state: directory
    mode: '0755'
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: create module xml
  template:
    src: module.xml.j2
    dest: "{{ app_path }}/modules/system/layers/base/org/mariadb/jdbc/main/module.xml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0644"

- name: copy jdbc module
  get_url:
    url: "{{ download_link }}/mariadb-jdbc.jar"
    dest: "{{ app_path }}/modules/system/layers/base/org/mariadb/jdbc/main/mariadb-jdbc.jar"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0644"