- name: remove default apt source
  file: 
    path: /etc/apt/sources.list
    state: absent

- name: create ustc sources
  template:
    src: ustc.sources.j2
    dest: /etc/apt/sources.list

- name: install require
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ packages }}"