- block:
  - name: set-cluster
    shell: kubectl config set-cluster {{ K8S_CLUSTER_NAME }} \
      --certificate-authority=ca.pem \
      --embed-certs=true \
      --server=https://192.168.1.111:6443 \
      --kubeconfig={{ CERT_NAME }}.kubeconfig
    args:
        chdir: "{{ CERT_DIR }}"
    delegate_to: localhost
  - name: set-credential
    shell: kubectl config set-credentials {{ COMPONENT_ROLE }} \
      --client-certificate={{ CERT_NAME }}.pem \
      --client-key={{ CERT_NAME }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ CERT_NAME }}.kubeconfig
    args:
        chdir: "{{ CERT_DIR }}"
    delegate_to: localhost
  - name: set-context
    shell: kubectl config set-context default \
      --cluster={{ K8S_CLUSTER_NAME }} \
      --user={{ COMPONENT_ROLE }} \
      --kubeconfig={{ CERT_NAME }}.kubeconfig
    args:
        chdir: "{{ CERT_DIR }}"
    delegate_to: localhost
  - name: set-context
    shell: kubectl config use-context default --kubeconfig={{ CERT_NAME }}.kubeconfig
    args:
        chdir: "{{ CERT_DIR }}"
    delegate_to: localhost
  - name: distribute certificates
    copy:
      src: "{{ CERT_DIR }}/{{ CERT_NAME }}.kubeconfig"
      dest: "{{ CONFIG_DIR }}/"
      owner: root
      group: root
      mode: "0400"
    when: not_distribute is not defined