- name: install requirements
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common', 'python-docker', 'python-apt']
    state: present
 
- name: import gpg key for docker repo
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: create docker apt repo
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker-ce

- name: install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: create docker group
  group:
    name: docker
    state: present

- name: add normal user into docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user is defined

- name: enable forward
  lineinfile:
    path: /lib/systemd/system/docker.service
    line: ExecStartPost=/sbin/iptables -I FORWARD -s 0.0.0.0/0 -j ACCEPT
    insertafter: '^ExecStart=/usr/bin/dockerd.*'

- name: configure image source for docker 
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - reboot docker

- name: Install docker-compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"
