- name: create folder
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root

- name: copy containerd binarys
  synchronize:
    src: "/home/nick/Downloads/containerd-bin/{{ item }}"
    dest: /usr/local/bin/
  with_items:
    - containerd
    - containerd-release
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-stress
    - ctr
 
- name: configure containerd
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml

- name: copy kubeconfig
  copy:
    src: "{{ ansible_hostname }}.kubeconfig"
    dest: /var/lib/kubelet/kubeconfig

- name: configure containerd service
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify:
    - systemd reload

- name: enable services at boot time
  file:
    src: /etc/systemd/system/{{ item }}
    dest: /etc/systemd/system/multi-user.target.wants/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - containerd.service