- name: Pull the image
  docker_image:
    name: "{{ registry }}/{{ image_name }}:{{ version }}"
    source: pull
    repository: "{{ image_name }}:{{ version }}"

- name: Create project folders
  file:
    path: "{{ PROJECT_DIR }}"
    state: directory
    owner: root
    group: root
    mode: 0644
    recurse: true

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ PROJECT_DIR }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  register: compose

- name: prepare service configuration
  template:
    src: "{{ image_name }}.yml.j2"
    dest: "{{ CONFIG_DIR }}/{{ image_name }}.yaml"
    owner: root
    group: root
    mode: 0644
  register: configuration

- name: start service
  shell: docker-compose -f "{{ PROJECT_DIR }}/docker-compose.yml" up -d --force-recreate
  when: compose is changed or configuration is changed