kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 65o4kyIEwZk4Qmq7JhnPa4nnSJH2+UuyztHsO51Qihc=
      - identity: {}