- name: Pull the image
  docker_image:
    name: registry.cn-hangzhou.aliyuncs.com/google_containers/{{ image_name }}:{{ version }}
    source: pull
    repository: "{{ image_name }}:{{ version }}"

- name: Create project folders
  file:
    path: "{{ PROJECT_DIR }}"
    state: directory
    owner: root
    group: root
    mode: 0644
    recurse: true

- name: prepare docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ PROJECT_DIR }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: prepare service configuration
  template:
    src: "{{ image_name }}.yml.j2"
    dest: "{{ CONFIG_DIR }}/{{ image_name }}.yaml"
    owner: root
    group: root
    mode: 0644