- name: install kubelet
  apt:
    name: kubelet
    state: present

- name: prepare config
  template:
    src: kubelet-config.yaml.j2
    dest: "{{ CONFIG_DIR }}/kubelet-config.yaml"
    owner: root
    group: root
    mode: 0644

- name: prepare service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  register: service_ready

- name: start service
  service:
    name: kubelet
    state: started
    enabled: yes
  when: register is changed
