- name: install kubelet
  apt:
    name: kubelet
    state: present
    allow_unauthenticated: yes

- name: prepare config
  template:
    src: kubelet-config.yaml.j2
    dest: "{{ CONFIG_DIR }}/kubelet-config.yaml"
    owner: root
    group: root
    mode: 0644
  register: config

- name: prepare service
  template:
    src: kubelet.service.j2
    dest: /lib/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  register: service_ready

- name: start service
  service:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: service_ready.changed is true or config.changed is true
