- name: prepare gitlab-ce volumes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: docker
  with_items:
    - /srv/gitlab/config
    - /srv/gitlab/logs
    - /srv/gitlab/data    

- name: start gitlab-ce docker 
  docker_container:
    name: "{{ gitlab_hostname }}"
    image: gitlab/gitlab-ce
    hostname: "{{ gitlab_hostname }}"
    restart: yes
    restart_policy: always
    # env:
    #   GITLAB_OMNIBUS_CONFIG="external_url {{ gitlab_hostname }}"
    ports:
      - 192.168.31.31:443:443
      - 192.168.31.31:80:80
      - 192.168.31.31:22:22
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
