---
- hosts: localhost
  vars_prompt:
    - name: CERT_NAME
      prompt: Enter the CERT_NAME
      default: admin
    - name: COMPONENT_ROLE
      prompt: Enter the cluster role
      default: admin
    - name: COMPONENT_GROUP
      prompt: Enter the group
      default: system:masters
  vars:
    - TLS_DIR: /opt/certs/k8s
    - not_distribute: true
    - CERT_DIR: /opt/certs/k8s
    - CERT_PROFILE: kubernetes
  tasks:
    - import_role:
        name: ca-client
    - import_role:
        name: kube-config-generator