---
- hosts: all
  vars:
     - logstash_ip: 192.168.1.1
     - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/filebeat"
     - image_name: 192.168.1.1:5000/filebeat
     - version: 7.5.1

  tasks:
    - import_role:
        name: filebeat-docker-compose