---
- hosts: masters
  vars:
    - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/kube-scheduler"
    - CERT_NAME: kubernetes
    - image_name: kube-scheduler
    - K8S_ROLE: system:kube-scheduler
  tasks:
    - import_role:
        name: ca-client
    - import_role:
        name: kube-config-generator
    - import_role:
        name: kube-scheduler-docker-compose
      vars:
        - CONFIG_DIR: "{{ PROJECT_DIR }}/config"