---
- hosts: workers
  vars:
    - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/kubelet"
    - CERT_NAME: kubelet-{{ ansible_hostname }}
    - COMPONENT_ROLE: "system:node:{{ ansible_hostname }}"
    - COMPONENT_GROUP: system:nodes
    - KUBERNETES_HOSTNAME: "{{ ansible_host }},{{ ansible_hostname }}"
    - CNI_PATH: /opt/cni/bin
  tasks:
    - name: Create CNI_PATH
      file:
        path: "{{ CNI_PATH }}"
        state: directory
        owner: root
        group: root
        mode: 0644
        recurse: true
    - name: Prepare cni bin
      unarchive:
        src: http://192.168.1.1/downloads/cni-plugins-linux-amd64-v0.8.5.tgz
        dest: "{{ CNI_PATH }}"
        remote_src: yes
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
        state: present
    - name: Add source
      apt_repository:
        repo: deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
        state: present
        filename: kubernetes
        update_cache: yes
    - import_role:
        name: ca-client
    - import_role:
        name: kube-config-generator
      vars:
        - CONFIG_DIR: "{{ PROJECT_DIR }}/config"
    - import_role:
        name: kubelet-service
      vars:
        - CONFIG_DIR: "{{ PROJECT_DIR }}/config"