---
- hosts: masters
  vars:
    - PROJECT_FOLDER: "{{ PROJECT_BASED_DIR }}/kube-api"
    - CERT_NAME: service-account
    - image_name: kube-apiserver
  tasks:
    - import_role:
        name: ca-client
    - import_role:
        name: kube-api-docker-compose