---
- hosts: masters
  vars:
    - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/kube-api"
    - image_name: kube-apiserver
  tasks:
    - import_role:
        name: ca-client
      vars:
        - CERT_NAME: kubernetes
        - COMPONENT_ROLE: "{{ ansible_hostname }}"
        - COMPONENT_GROUP: kubernetes
        - KUBERNETES_HOSTNAME: "10.32.0.1,{{ ansible_host }},kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"
    - import_role:
        name: ca-client
      vars:
        - CERT_NAME: service-account
        - COMPONENT_ROLE: "{{ ansible_hostname }}"
        - COMPONENT_GROUP: kubernetes
    - import_role:
        name: kube-api-docker-compose