---
- hosts: masters
  vars:
    - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/kube-controller-manager"
    - CERT_NAME: kube-controller-manager
    - image_name: kube-controller-manager
    - K8S_ROLE: system:kube-controller-manager
    - COMPONENET_ROLE: system:kube-controller-manager
    - CONTAINER_CONFIG_DIR: "/etc/kube-controller-manager"
  tasks:
    - import_role:
        name: ca-client
    - import_role:
        name: kube-config-generator
      vars:
        - CONFIG_DIR: "{{ PROJECT_DIR }}/config"
    - import_role:
        name: kube-controller-manager-docker-compose
      vars:
        - CONFIG_DIR: "{{ PROJECT_DIR }}/config"