---
- hosts: etcds
  vars:
    - PROJECT_DIR: "{{ PROJECT_BASED_DIR }}/etcd"
    - CERT_NAME: etcd
    - version: 3.4.3-0
    - COMPONENT_ROLE: "{{ ansible_hostname }}"
    - COMPONENT_GROUP: kubernetes
    - registry: 192.168.1.1:5000
  tasks:
    - import_role:
        name: ca-client
    - import_role:
        name: etcd-docker-compose