- name: add apt key for nodejs source
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs source
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_11.x {{ ansible_lsb.codename }} main"
    state: present
    filename: nodesource

- name: install nodejs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nodejs
